<%@ page import="mg.atelier.model.ReparationTypePrice" %>
<%@ page import="java.util.List" %>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Liste des Types de Reparation</title>
    <link rel="stylesheet" href="/assets/css/bootstrap.min.css">
    <style>
        body {
            padding-top: 56px;
        }
        .navbar {
            margin-bottom: 20px;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="#">Atelier</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="/index">Accueil</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/component/all">Composants</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/client/all">Clients</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/reparationType/all">Type de Reparation</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/reparation/all">Reparation</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container">
        <h1>Voici la liste des types de reparation</h1>
        <% 
            String success = (String) request.getAttribute("success");
            if (success != null && !success.isEmpty()) {
        %>
            <div class="alert alert-success" role="alert">
                <%= success %>
            </div>
        <% 
            } 
        %>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Type</th>
                    <th>Composant a remplacer</th>
                    <th>Duree</th>
                    <th>Prix</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody id="reparationTypeTableBody">
                <% 
                    List<ReparationTypePrice> allReparationTypes = (List<ReparationTypePrice>) application.getAttribute("reparationTypes");
                    for (ReparationTypePrice reparationTypePrice : allReparationTypes) {
                %>
                    <tr class="reparationType-row">
                        <td><%= reparationTypePrice.getReparationType().getIdReparationType() %></td>
                        <td><%= reparationTypePrice.getReparationType().getType() %></td>
                        <td><%= reparationTypePrice.getReparationType().getComponent() != null ? reparationTypePrice.getReparationType().getComponent().getName() : "N/A" %></td>
                        <td><%= reparationTypePrice.getReparationType().getCleanDuration() %></td>
                        <td><%= reparationTypePrice.getPrice() %></td>
                        <td>
                            <form action="/reparationType/prepareUpdatePrice" method="get">
                                <input type="hidden" name="id" value="<%= reparationTypePrice.getIdReparationTypePrice() %>">
                                <input type="hidden" name="price" value="<%= reparationTypePrice.getPrice() %>">
                                <button type="submit" class="btn btn-primary">Modifier le prix</button>
                            </form>
                        </td>
                    </tr>
                <% 
                    } 
                %>
            </tbody>
        </table>
        <nav aria-label="Page navigation">
            <ul class="pagination" id="pagination">
                <!-- Pagination links will be generated by JavaScript -->
            </ul>
        </nav>
        <a href="/reparationType/prepareInsert" class="btn bg-dark" style="color : white;">Ajouter un type de reparation</a>
    </div>
    <script src="/assets/js/jquery-3.5.1.slim.min.js"></script>
    <script src="/assets/js/popper.min.js"></script>
    <script src="/assets/js/bootstrap.min.js"></script>
    <script src="/assets/js/script.js"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const rowsPerPage = 20;
            const rows = document.querySelectorAll('.reparationType-row');
            const pagination = document.getElementById('pagination');
            const totalPages = Math.ceil(rows.length / rowsPerPage);

            createPagination(rowsPerPage , rows , pagination,totalPages);
        });
    </script>
</body>
</html>